# This is a basic workflow to help you get started with Actions

name: Push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, action-test-1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      # Set up ssh-agent to push to pantheon
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}

      # Runs a single command using the runners shell
      - name: Add pantheon git remote
        run: git remote add pantheon ssh://codeserver.dev.18326fa2-af98-4055-89ad-ccfa41cb679a@codeserver.dev.18326fa2-af98-4055-89ad-ccfa41cb679a.drush.in:2222/~/repository.git

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          CURRENT_BRANCH: ${{ github.ref }}
        run: |
          echo "$CURRENT_BRANCH"
          git push pantheon
